baseURL = "http://perfectly-spherical.com/"
languageCode = "en-us"
title = "perfectly spherical"
theme = "sk3"
noTimes = "true"

# enable raw html in markdown
[markup.goldmark.renderer]
unsafe= true

[Params]
subtitle = "Game Design In Theory"

opengraph   = true
twittercards = true
description = "Game Design In Theory"
title       = "perfectly spherical"

custom_css = ["/css/sidebar.css"]
favicon = "/spherical-terminal-orange.svg"

[Params.color]
bg     = "#181010"
border = "#ffb000"
link   = "#ffcc00"
text   = "#ffb000"

[Params.socialshare]
facebook  = false
instagram = false
linkedin  = false
pinterest = false
reddit    = false
telegram  = false
twitter   = true
vk        = false

[Params.sociallink]
  rss            = true
  twitter        = "dan_breez"

[Params.card]
date    = true
summary = true
width   = "32%"
